# Generated by Django 3.2.17 on 2023-02-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='idDelivered',
            new_name='isDelivered',
        ),
    ]
